trigger:
- master

pool: Default

steps:
- task: DownloadSecureFile@1
  name: caCertificate
  inputs:
    secureFile: 'certix.pfx'
    retryCount: '3'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Import-PfxCertificate -FilePath $(caCertificate.secureFilePath) -CertStoreLocation Cert:\LocalMachine\My'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Import-PfxCertificate -FilePath $(caCertificate.secureFilePath) -CertStoreLocation Cert:\LocalMachine\Root'