trigger:
- master

pool: Default

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '-v n --filter TestCategory=first'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '-v n --filter TestCategory=second'
        
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '-v n --filter TestCategory=third'
  - task: SpecFlowPlus@0
    inputs:
      generatorSource: 'TestAssembly'
      testAssemblyFilePath: '..\..\2\s\Solution1\SpecProj\bin\Debug\netcoreapp3.1\SpecProj.dll'
      projectName: 'asd'
      testExecutionJson: '..\..\2\s\Solution1\SpecProj\bin\Debug\netcoreapp3.1\TestExecution.json'
    enabled: true
    continueOnError: true
    condition: always()
    
