trigger:
- master

pool: Default

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**\SpecProj.csproj'
    displayName: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '--no-build -v m --filter TestCategory=first'
    displayName: 'test 1'
    continueOnError: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '--no-build -v m --filter TestCategory=second'
    displayName: 'test 2'
    continueOnError: true
        
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '--no-build -v m --filter TestCategory=third'
    displayName: 'test 3'
    continueOnError: true
  - task: SpecFlowPlus@0
    inputs:
      generatorSource: 'TestAssembly'
      testAssemblyFilePath: '..\..\2\s\Solution1\SpecProj\bin\Debug\netcoreapp3.1\SpecProj.dll'
      projectName: 'asd'
      testExecutionJson: '..\..\2\s\Solution1\SpecProj\bin\Debug\netcoreapp3.1\TestExecution.json'
    enabled: true
    continueOnError: true
    condition: always()
    
