trigger:
- master

pool: Default

steps:
- task: DownloadSecureFile@1
  name: caCertificate
  inputs:
    secureFile: 'kakel.txt'
    retryCount: '3'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'cat $(caCertificate.secureFilePath)'