trigger: none

pool: Default

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**\SpecProj.csproj'
    displayName: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '--no-build -v m --filter TestCategory=first'
    displayName: 'test 1'
    continueOnError: true
    
