trigger: none

pool: Default

parameters:
- name: category
  type: string
  default: 'second'

variables:
- name: defaultNumber
  value: 'second' 
- name: zmienna
  ${{ if not(eq(parameters.category, '$(defaultNumber)')) }}:
    value: ${{ parameters.category }}
- group: 'SecretyLola_${{ parameters.category }}'

resources:
  pipelines:
  - pipeline: something
    source: 'michelle pfeiffer'
    trigger: true

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**\SpecProj.csproj'
    displayName: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '--no-build -v m --filter TestCategory=${{ variables.SuperSekret }}'
    displayName: 'test 2'
    continueOnError: true
    
