trigger: none

pool: Default

variables:
- name: one
  value: second 

resources:
  pipelines:
  - pipeline: something
    source: 'michelle pfeiffer'
    trigger: true

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**\SpecProj.csproj'
    displayName: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '--no-build -v m --filter TestCategory=${{ variables.one }}'
    displayName: 'test 2'
    continueOnError: true
    
