trigger: none

pool: Default

resources:
  pipelines:
  - pipeline: something
    source: 'michelle pfeiffer'
    trigger:
        branches:
          - 'staszek_nowakowski_tomek'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**\SpecProj.csproj'
    displayName: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**\SpecProj.csproj'
      arguments: '--no-build -v m --filter TestCategory=second'
    displayName: 'test 2'
    continueOnError: true
    
